import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import {
  CLUSTERS,
  UNITS,
  LOCATIONS,
  CASUALTY_CONDITIONS,
  POSITIONS,
  USER_TYPES,
  EVENT_STATUSES,
  DAMAGE_CONDITION,
} from '@/types/constants';
import 'dotenv/config';

const adapter = new PrismaPg({ connectionString: process.env.SHADOW_DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

// ─── Quarter → approximate NSED drill dates ───────────────
// NSED is held every last Thursday of Jan, Apr, Jul, Oct
const QUARTER_DATES: Record<string, { started_at: Date; ended_at: Date }> = {
  'Q1 2025': {
    started_at: new Date('2025-01-23T08:00:00+08:00'),
    ended_at: new Date('2025-01-23T17:00:00+08:00'),
  },
  'Q2 2025': {
    started_at: new Date('2025-04-24T08:00:00+08:00'),
    ended_at: new Date('2025-04-24T17:00:00+08:00'),
  },
  'Q3 2025': {
    started_at: new Date('2025-07-24T08:00:00+08:00'),
    ended_at: new Date('2025-07-24T17:00:00+08:00'),
  },
  'Q4 2025': {
    started_at: new Date('2025-10-23T08:00:00+08:00'),
    ended_at: new Date('2025-10-23T17:00:00+08:00'),
  },
  'Q1 2026': {
    started_at: new Date('2026-01-22T08:00:00+08:00'),
    ended_at: new Date('2026-01-22T17:00:00+08:00'),
  },
};

// ─── Historical report data from Monday.com export ───────
const REPORT_DATA = [
  {
    quarter: 'Q1 2025',
    cluster: 'Pedro Gil',
    unit: 'College of Nursing',
    faculty_members: 17,
    admin_members: 14,
    reps_members: 0,
    ra_members: 0,
    students: 115,
    philcare_staff: 4,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 1,
    guests: 5,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '2019699021',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Frederick David E. Beltran',
    encoder_position: 'Other',
    unit: 'NIH',
    faculty_members: 0,
    admin_members: 12,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 2,
    casualties_count: 0,
    external_item_id: '1985307586',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Paolo Robert P. Bueno',
    encoder_position: 'Other',
    unit: 'College of Pharmacy',
    faculty_members: 12,
    admin_members: 16,
    reps_members: 0,
    ra_members: 4,
    students: 85,
    philcare_staff: 5,
    security_personnel: 2,
    construction_workers: 7,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 4,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '1985309416',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Aileen Regaspi',
    encoder_position: 'Other',
    unit: 'CAMP',
    faculty_members: 21,
    admin_members: 13,
    reps_members: 3,
    ra_members: 1,
    students: 122,
    philcare_staff: 3,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '1985309689',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Maricar B. Paras-Ong',
    encoder_position: 'Other',
    unit: 'College of Dentistry',
    faculty_members: 23,
    admin_members: 4,
    reps_members: 1,
    ra_members: 0,
    students: 118,
    philcare_staff: 6,
    security_personnel: 3,
    construction_workers: 1,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 22,
    guests: 66,
    missing_count: 0,
    casualties_count: 0,
    casualties_detail: 'No injured',
    external_item_id: '1985312647',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Rowel Malimban',
    encoder_position: 'Other',
    unit: 'CPH',
    faculty_members: 9,
    admin_members: 32,
    reps_members: 16,
    ra_members: 2,
    students: 38,
    philcare_staff: 8,
    security_personnel: 2,
    construction_workers: 2,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 3,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '1985313645',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'ROSELLE DEL CARMEN',
    encoder_position: 'Other',
    unit: 'College of Nursing',
    faculty_members: 3,
    admin_members: 6,
    reps_members: 1,
    ra_members: 2,
    students: 114,
    philcare_staff: 4,
    security_personnel: 2,
    construction_workers: 0,
    tenants: 15,
    health_workers: 0,
    non_academic_staff: 2,
    guests: 1,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '1985320569',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Padre Faura',
    encoder_name: 'Carlota P. Surat',
    encoder_position: 'Other',
    unit: 'CAS',
    faculty_members: 23,
    admin_members: 29,
    reps_members: 0,
    ra_members: 4,
    students: 429,
    philcare_staff: 17,
    security_personnel: 8,
    construction_workers: 27,
    tenants: 5,
    health_workers: 0,
    non_academic_staff: 27,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    casualties_detail: 'none',
    external_item_id: '1985308627',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Padre Faura',
    encoder_name: 'Janyn T. Pagtananan',
    encoder_position: 'Other',
    unit: 'Joaquin Gonzales Compound',
    faculty_members: 0,
    admin_members: 5,
    reps_members: 1,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '1985321602',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Taft',
    encoder_name: 'Robelyn N. Aguilar',
    encoder_position: 'Other',
    unit: 'Central Administration (CAD)',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 2,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 3,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '1985272377',
  },
  {
    quarter: 'Q1 2025',
    cluster: 'Taft',
    encoder_name: 'Martin R. Racza',
    encoder_position: 'Other',
    unit: 'Central Administration (CAD)',
    faculty_members: 0,
    admin_members: 3,
    reps_members: 2,
    ra_members: 2,
    students: 0,
    philcare_staff: 1,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 1,
    casualties_detail: 'Charito D. Madrideo',
    external_item_id: '1985313602',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Viesca, Vilma Q',
    encoder_position: 'Head of Unit',
    unit: '',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 12,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 2,
    non_academic_staff: 12,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '10:19 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Emilio Apo Jr',
    encoder_position: 'Other',
    unit: '670, Ermita, City Of Manila, 1000 Metro Manila, Philippines',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 40,
    non_academic_staff: 33,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    casualties_detail: '2',
    external_item_id: '10:21 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Thahanni Apryll T. Bajunaid',
    encoder_position: 'Other',
    unit: '',
    faculty_members: 0,
    admin_members: 246,
    reps_members: 246,
    ra_members: 246,
    students: 246,
    philcare_staff: 246,
    security_personnel: 246,
    construction_workers: 246,
    tenants: 246,
    health_workers: 246,
    non_academic_staff: 246,
    guests: 246,
    missing_count: 246,
    casualties_count: 0,
    external_item_id: '08:54 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Thahanni Apryll T. Bajunaid',
    encoder_position: 'Other',
    unit: '670, Ermita, City Of Manila, 1000 Metro Manila, Philippines',
    faculty_members: 0,
    admin_members: 85,
    reps_members: 85,
    ra_members: 85,
    students: 85,
    philcare_staff: 85,
    security_personnel: 85,
    construction_workers: 85,
    tenants: 85,
    health_workers: 85,
    non_academic_staff: 85,
    guests: 85,
    missing_count: 85,
    casualties_count: 0,
    external_item_id: '08:57 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Thahanni Apryll T. Bajunaid',
    encoder_position: 'Other',
    unit: '670, Ermita, City Of Manila, 1000 Metro Manila, Philippines',
    faculty_members: 0,
    admin_members: 136,
    reps_members: 136,
    ra_members: 136,
    students: 136,
    philcare_staff: 136,
    security_personnel: 136,
    construction_workers: 136,
    tenants: 136,
    health_workers: 136,
    non_academic_staff: 136,
    guests: 136,
    missing_count: 136,
    casualties_count: 0,
    external_item_id: '08:58 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Thahanni Apryll T. Bajunaid',
    encoder_position: 'Other',
    unit: '670, Ermita, City Of Manila, 1000 Metro Manila, Philippines',
    faculty_members: 0,
    admin_members: 590,
    reps_members: 590,
    ra_members: 590,
    students: 590,
    philcare_staff: 590,
    security_personnel: 590,
    construction_workers: 590,
    tenants: 590,
    health_workers: 590,
    non_academic_staff: 590,
    guests: 590,
    missing_count: 590,
    casualties_count: 0,
    casualties_detail: '550',
    external_item_id: '09:06 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Thahanni Apryll T. Bajunaid',
    encoder_position: 'Other',
    unit: '670, Ermita, City Of Manila, 1000 Metro Manila, Philippines',
    faculty_members: 0,
    admin_members: 73,
    reps_members: 73,
    ra_members: 73,
    students: 73,
    philcare_staff: 73,
    security_personnel: 73,
    construction_workers: 73,
    tenants: 73,
    health_workers: 73,
    non_academic_staff: 73,
    guests: 73,
    missing_count: 73,
    casualties_count: 0,
    casualties_detail: '500',
    external_item_id: '09:09 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Thahanni Apryll T. Bajunaid',
    encoder_position: 'Other',
    unit: '670, Ermita, City Of Manila, 1000 Metro Manila, Philippines',
    faculty_members: 0,
    admin_members: 73,
    reps_members: 73,
    ra_members: 73,
    students: 73,
    philcare_staff: 73,
    security_personnel: 73,
    construction_workers: 73,
    tenants: 73,
    health_workers: 73,
    non_academic_staff: 73,
    guests: 73,
    missing_count: 73,
    casualties_count: 0,
    casualties_detail: '500',
    external_item_id: '09:14 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Thahanni Apryll T. Bajunaid',
    encoder_position: 'Other',
    unit: '670, Ermita, City Of Manila, 1000 Metro Manila, Philippines',
    faculty_members: 0,
    admin_members: 50,
    reps_members: 50,
    ra_members: 50,
    students: 50,
    philcare_staff: 50,
    security_personnel: 50,
    construction_workers: 50,
    tenants: 50,
    health_workers: 50,
    non_academic_staff: 50,
    guests: 50,
    missing_count: 50,
    casualties_count: 0,
    casualties_detail: '43',
    external_item_id: '09:15 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Thahanni Apryll T. Bajunaid',
    encoder_position: 'Other',
    unit: '670, Ermita, City Of Manila, 1000 Metro Manila, Philippines',
    faculty_members: 0,
    admin_members: 56,
    reps_members: 56,
    ra_members: 56,
    students: 56,
    philcare_staff: 56,
    security_personnel: 56,
    construction_workers: 56,
    tenants: 56,
    health_workers: 56,
    non_academic_staff: 56,
    guests: 56,
    missing_count: 56,
    casualties_count: 0,
    external_item_id: '09:16 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Thahanni Apryll T. Bajunaid',
    encoder_position: 'Other',
    unit: '670, Ermita, City Of Manila, 1000 Metro Manila, Philippines',
    faculty_members: 0,
    admin_members: 150,
    reps_members: 150,
    ra_members: 150,
    students: 150,
    philcare_staff: 150,
    security_personnel: 150,
    construction_workers: 150,
    tenants: 150,
    health_workers: 150,
    non_academic_staff: 150,
    guests: 150,
    missing_count: 150,
    casualties_count: 0,
    external_item_id: '09:18 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Thahanni Apryll T. Bajunaid',
    encoder_position: 'Other',
    unit: '670, Ermita, City Of Manila, 1000 Metro Manila, Philippines',
    faculty_members: 0,
    admin_members: 69,
    reps_members: 69,
    ra_members: 69,
    students: 69,
    philcare_staff: 69,
    security_personnel: 69,
    construction_workers: 69,
    tenants: 69,
    health_workers: 69,
    non_academic_staff: 69,
    guests: 69,
    missing_count: 69,
    casualties_count: 0,
    casualties_detail: '2',
    external_item_id: '09:20 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Thahanni Apryll T. Bajunaid',
    encoder_position: 'Other',
    unit: '670, Ermita, City Of Manila, 1000 Metro Manila, Philippines',
    faculty_members: 0,
    admin_members: 71,
    reps_members: 71,
    ra_members: 71,
    students: 71,
    philcare_staff: 71,
    security_personnel: 71,
    construction_workers: 71,
    tenants: 71,
    health_workers: 71,
    non_academic_staff: 71,
    guests: 71,
    missing_count: 71,
    casualties_count: 0,
    casualties_detail: '2234',
    external_item_id: '09:23 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Thahanni Apryll T. Bajunaid',
    encoder_position: 'Other',
    unit: '670, Ermita, City Of Manila, 1000 Metro Manila, Philippines',
    faculty_members: 0,
    admin_members: 12,
    reps_members: 12,
    ra_members: 12,
    students: 12,
    philcare_staff: 12,
    security_personnel: 12,
    construction_workers: 12,
    tenants: 12,
    health_workers: 12,
    non_academic_staff: 12,
    guests: 12,
    missing_count: 12,
    casualties_count: 0,
    external_item_id: '09:24 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Thahanni Apryll T. Bajunaid',
    encoder_position: 'Other',
    unit: '670, Ermita, City Of Manila, 1000 Metro Manila, Philippines',
    faculty_members: 0,
    admin_members: 172,
    reps_members: 172,
    ra_members: 172,
    students: 172,
    philcare_staff: 172,
    security_personnel: 172,
    construction_workers: 172,
    tenants: 172,
    health_workers: 172,
    non_academic_staff: 172,
    guests: 172,
    missing_count: 172,
    casualties_count: 0,
    casualties_detail: '5',
    external_item_id: '09:25 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Filipina Belinda Gordoncillo',
    encoder_position: 'Head of Unit',
    unit: 'College of Nursing',
    faculty_members: 0,
    admin_members: 4,
    reps_members: 13,
    ra_members: 4,
    students: 0,
    philcare_staff: 1,
    security_personnel: 5,
    construction_workers: 1,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '09:06 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Mary Mae L. Bico',
    encoder_position: 'Head of Unit',
    unit: 'UP Manila Phi House Dormitory',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 1,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 1,
    construction_workers: 1,
    tenants: 0,
    health_workers: 8,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    casualties_detail: '2',
    external_item_id: '09:54 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Anna Marie demeterio',
    encoder_position: 'Other',
    unit: 'College of  Public Health',
    faculty_members: 0,
    admin_members: 5,
    reps_members: 32,
    ra_members: 8,
    students: 5,
    philcare_staff: 1,
    security_personnel: 8,
    construction_workers: 3,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 35,
    casualties_count: 0,
    external_item_id: '09:12 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'MA. DIANE MONIQUE A. HIJOSA',
    encoder_position: 'Head of Unit',
    unit: 'UP Manila Dorm',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 2,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 1,
    construction_workers: 1,
    tenants: 0,
    health_workers: 26,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    casualties_detail: '2',
    external_item_id: '09:58 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Leslie Ligsay',
    encoder_position: 'Other',
    unit: 'College of Medicine',
    faculty_members: 0,
    admin_members: 20,
    reps_members: 69,
    ra_members: 7,
    students: 4,
    philcare_staff: 47,
    security_personnel: 21,
    construction_workers: 8,
    tenants: 16,
    health_workers: 0,
    non_academic_staff: 2,
    guests: 0,
    missing_count: 5,
    casualties_count: 0,
    external_item_id: '09:17 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'FREDERICK BELTRAN',
    encoder_position: 'Other',
    unit: 'National Institutes of Health',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 10,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '09:08 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Padre Faura',
    encoder_name: 'Janyn Pagtananan',
    encoder_position: 'Other',
    unit: 'Joaquin Gonzales Building',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 5,
    ra_members: 1,
    students: 0,
    philcare_staff: 0,
    security_personnel: 2,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '09:42 AM',
  },
  {
    quarter: 'Q2 2025',
    cluster: 'Taft',
    encoder_name: 'Jorel Manalo',
    encoder_position: 'Other',
    unit: 'HXHP+R2J, Padre Faura St, Ermita, City Of Manila, 1000 Metro Manila, Philippines',
    faculty_members: 0,
    admin_members: 4,
    reps_members: 54,
    ra_members: 2,
    students: 1,
    philcare_staff: 0,
    security_personnel: 7,
    construction_workers: 2,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 46,
    missing_count: 0,
    casualties_count: 0,
    casualties_detail: '8',
    external_item_id: '10:33 AM',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Ma. Diane Monique A. Hijosa',
    encoder_position: 'Head of Unit',
    unit: 'UP Manila Dorm',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 3,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 1,
    construction_workers: 1,
    tenants: 0,
    health_workers: 36,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '09:34 AM',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Frederick David E. Beltran',
    encoder_position: 'Other',
    unit: 'National Institutes of Health',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 13,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '04:05 PM',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Aileen Regaspi',
    encoder_position: 'Other',
    unit: 'College of Allied Medical Professions',
    faculty_members: 0,
    admin_members: 14,
    reps_members: 14,
    ra_members: 1,
    students: 0,
    philcare_staff: 92,
    security_personnel: 2,
    construction_workers: 1,
    tenants: 9,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '04:09 PM',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Maricar B. Paras-Ong',
    encoder_position: 'Other',
    unit: 'College of Dentistry',
    faculty_members: 0,
    admin_members: 22,
    reps_members: 20,
    ra_members: -1,
    students: 0,
    philcare_staff: 212,
    security_personnel: 7,
    construction_workers: 3,
    tenants: 2,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 4,
    missing_count: 12,
    casualties_count: 0,
    external_item_id: '04:14 PM',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Clark Reynald Esperanza',
    encoder_position: 'Other',
    unit: 'National Institutes of Health',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 60,
    ra_members: 6,
    students: 0,
    philcare_staff: 0,
    security_personnel: 3,
    construction_workers: 3,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 1,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '04:16 PM',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Earl Francis Sumile',
    encoder_position: 'Other',
    unit: 'College of Nursing',
    faculty_members: 0,
    admin_members: 11,
    reps_members: 13,
    ra_members: 3,
    students: 0,
    philcare_staff: 65,
    security_personnel: 5,
    construction_workers: 1,
    tenants: 3,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 1,
    missing_count: 1,
    casualties_count: 0,
    external_item_id: '04:22 PM',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Lorelie Alcazar',
    encoder_position: 'Other',
    unit: 'College of Medicine',
    faculty_members: 0,
    admin_members: 16,
    reps_members: 66,
    ra_members: 2,
    students: 14,
    philcare_staff: 118,
    security_personnel: 18,
    construction_workers: 11,
    tenants: 19,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '04:23 PM',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Mary Mae Bico',
    encoder_position: 'Head of Unit',
    unit: 'UP Manila Phi House Dormitory',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 2,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 1,
    tenants: 0,
    health_workers: 22,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    casualties_detail: '1',
    external_item_id: '04:28 PM',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Ma. Diane Monique A. Hijosa',
    encoder_position: 'Head of Unit',
    unit: 'UP Manila Dorm',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 2,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 1,
    tenants: 0,
    health_workers: 34,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 1,
    casualties_count: 0,
    casualties_detail: '1',
    external_item_id: '04:52 PM',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Padre Faura',
    encoder_name: 'Janyn Pagtananan',
    encoder_position: 'Other',
    unit: 'Joaquin Gonzales Building',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 5,
    ra_members: 1,
    students: 0,
    philcare_staff: 0,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '04:04 PM',
  },
  {
    quarter: 'Q3 2025',
    cluster: 'Padre Faura',
    encoder_name: 'Justine Paul S. Monsanto',
    encoder_position: 'Other',
    unit: 'Campus Planning, Development, and Management Office',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 25,
    ra_members: 0,
    students: 0,
    philcare_staff: 11,
    security_personnel: 1,
    construction_workers: 1,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 4,
    casualties_count: 0,
    external_item_id: '04:18 PM',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Lorelie Alcazar',
    encoder_position: 'Other',
    unit: 'College of Medicine',
    faculty_members: 0,
    admin_members: 23,
    reps_members: 77,
    ra_members: 1,
    students: 8,
    philcare_staff: 408,
    security_personnel: 24,
    construction_workers: 10,
    tenants: 21,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 1,
    missing_count: 21,
    casualties_count: 0,
    external_item_id: '09:15 AM',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Mary Mae L. Bico',
    encoder_position: 'Head of Unit',
    unit: 'UP Manila Phi House Dormitory',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 1,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 1,
    construction_workers: 1,
    tenants: 0,
    health_workers: 21,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '10:06 AM',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Lalaine Salaysay',
    encoder_position: 'Other',
    unit: 'College of Dentistry',
    faculty_members: 0,
    admin_members: 20,
    reps_members: 24,
    ra_members: 0,
    students: 0,
    philcare_staff: 131,
    security_personnel: 7,
    construction_workers: 3,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 24,
    missing_count: 38,
    casualties_count: 0,
    external_item_id: '09:04 AM',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Filipina Gordoncillo',
    encoder_position: 'Head of Unit',
    unit: 'College of Nursing',
    faculty_members: 0,
    admin_members: 5,
    reps_members: 12,
    ra_members: 4,
    students: 0,
    philcare_staff: 70,
    security_personnel: 5,
    construction_workers: 1,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 1,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '09:09 AM',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Kenneth Ervin T. Quintos',
    encoder_position: 'Other',
    unit: 'College of Pharmacy',
    faculty_members: 0,
    admin_members: 7,
    reps_members: 17,
    ra_members: 0,
    students: 0,
    philcare_staff: 73,
    security_personnel: 4,
    construction_workers: 2,
    tenants: 7,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '09:10 AM',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Clark Reynald A. Esperanza',
    encoder_position: 'Other',
    unit: 'National Institutes of Health',
    faculty_members: 0,
    admin_members: 5,
    reps_members: 76,
    ra_members: 7,
    students: 3,
    philcare_staff: 0,
    security_personnel: 5,
    construction_workers: 2,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 2,
    guests: 0,
    missing_count: 7,
    casualties_count: 0,
    external_item_id: '09:17 AM',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Frederick David E. Beltran',
    encoder_position: 'Other',
    unit: 'National Institutes of Health',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 13,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '09:27 AM',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Pedro Gil',
    encoder_name: 'Aileen Regaspi',
    encoder_position: 'Other',
    unit: 'College of Allied Medical Professions',
    faculty_members: 0,
    admin_members: 7,
    reps_members: 15,
    ra_members: 3,
    students: 0,
    philcare_staff: 142,
    security_personnel: 2,
    construction_workers: 1,
    tenants: 11,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '09:11 AM',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Padre Faura',
    encoder_name: 'Justine Paul Monsanto',
    encoder_position: 'Other',
    unit: 'Campus Planning, Development, and Management Office',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 25,
    ra_members: 0,
    students: 0,
    philcare_staff: 10,
    security_personnel: 1,
    construction_workers: 1,
    tenants: 4,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '09:20 AM',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Padre Faura',
    encoder_name: 'JOHN NICO DE LEON',
    encoder_position: 'Other',
    unit: 'College of Arts and Sciences',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 0,
    ra_members: 0,
    students: 2,
    philcare_staff: 630,
    security_personnel: 23,
    construction_workers: 8,
    tenants: 33,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 31,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '09:11 AM',
  },
  {
    quarter: 'Q4 2025',
    cluster: 'Padre Faura',
    encoder_name: 'Janyn Pagtananan',
    encoder_position: 'Other',
    unit: 'Joaquin Gonzales Building',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 5,
    ra_members: 2,
    students: 0,
    philcare_staff: 0,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '09:09 AM',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    encoder_name: 'Ma. Diane Monique A. Hijosa',
    encoder_position: 'Head of Unit',
    unit: 'UP Manila Dorm',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 2,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 1,
    construction_workers: 1,
    tenants: 3,
    health_workers: 21,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '04:00 PM',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    encoder_name: 'Mary Mae L. Bico',
    encoder_position: 'Head of Unit',
    unit: 'UP Manila Phi House Dormitory',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 0,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 1,
    construction_workers: 1,
    tenants: 0,
    health_workers: 13,
    non_academic_staff: 0,
    guests: 2,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '04:02 PM',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    encoder_name: 'filipina benilda gordoncillo',
    encoder_position: 'Other',
    unit: 'College of Nursing',
    faculty_members: 0,
    admin_members: 5,
    reps_members: 12,
    ra_members: 3,
    students: 0,
    philcare_staff: 106,
    security_personnel: 4,
    construction_workers: 1,
    tenants: 0,
    health_workers: 2,
    non_academic_staff: 0,
    guests: 1,
    missing_count: 2,
    casualties_count: 0,
    external_item_id: '03:51 PM',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    encoder_name: 'Maricar B. Paras-Ong',
    encoder_position: 'Other',
    unit: 'College of Dentistry',
    faculty_members: 0,
    admin_members: 37,
    reps_members: 7,
    ra_members: 1,
    students: 0,
    philcare_staff: 107,
    security_personnel: 7,
    construction_workers: 3,
    tenants: 5,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 20,
    missing_count: 63,
    casualties_count: 0,
    external_item_id: '03:44 PM',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    encoder_name: 'Aileen Regaspi',
    encoder_position: 'Other',
    unit: 'College of Allied Medical Professions',
    faculty_members: 0,
    admin_members: 12,
    reps_members: 11,
    ra_members: 3,
    students: 0,
    philcare_staff: 87,
    security_personnel: 3,
    construction_workers: 1,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 4,
    casualties_count: 0,
    external_item_id: '03:42 PM',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    encoder_name: 'Clark Reynald A. Esperanza',
    encoder_position: 'Other',
    unit: 'National Institutes of Health',
    faculty_members: 0,
    admin_members: 3,
    reps_members: 161,
    ra_members: 28,
    students: 15,
    philcare_staff: 0,
    security_personnel: 5,
    construction_workers: 2,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '03:41 PM',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    encoder_name: 'Kenneth Quintos',
    encoder_position: 'Other',
    unit: 'College of Pharmacy',
    faculty_members: 0,
    admin_members: 16,
    reps_members: 20,
    ra_members: 1,
    students: 7,
    philcare_staff: 107,
    security_personnel: 4,
    construction_workers: 2,
    tenants: 6,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '03:40 PM',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    encoder_name: 'Leslie Anne Ligsay',
    encoder_position: 'Other',
    unit: 'College of Medicine',
    faculty_members: 0,
    admin_members: 49,
    reps_members: 103,
    ra_members: 3,
    students: 7,
    philcare_staff: 250,
    security_personnel: 27,
    construction_workers: 9,
    tenants: 22,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 2,
    missing_count: 1,
    casualties_count: 0,
    external_item_id: '03:38 PM',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    encoder_name: 'Frederick David E. Beltran',
    encoder_position: 'Other',
    unit: 'National Institutes of Health',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 9,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 0,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '03:35 PM',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Pedro Gil',
    encoder_name: 'Jane B. Gegonia',
    encoder_position: 'Other',
    unit: 'College of  Public Health',
    faculty_members: 0,
    admin_members: 13,
    reps_members: 31,
    ra_members: 8,
    students: 8,
    philcare_staff: 59,
    security_personnel: 8,
    construction_workers: 4,
    tenants: 42,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '11:00 AM',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Padre Faura',
    encoder_name: 'Marybel P. Caasi',
    encoder_position: 'Head of Unit',
    unit: 'Joaquin Gonzales Building',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 3,
    ra_members: 3,
    students: 0,
    philcare_staff: 0,
    security_personnel: 1,
    construction_workers: 0,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '03:56 PM',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Padre Faura',
    encoder_name: 'JUSTINE PAUL MONSANTO',
    encoder_position: 'Other',
    unit: 'Campus Planning, Development, and Management Office',
    faculty_members: 0,
    admin_members: 0,
    reps_members: 26,
    ra_members: 0,
    students: 0,
    philcare_staff: 0,
    security_personnel: 1,
    construction_workers: 1,
    tenants: 0,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 0,
    casualties_count: 0,
    external_item_id: '03:51 PM',
  },
  {
    quarter: 'Q1 2026',
    cluster: 'Padre Faura',
    encoder_name: 'Ronald Cabigting',
    encoder_position: 'Other',
    unit: 'College of Arts and Sciences',
    faculty_members: 0,
    admin_members: 25,
    reps_members: 30,
    ra_members: 2,
    students: 2,
    philcare_staff: 593,
    security_personnel: 10,
    construction_workers: 8,
    tenants: 25,
    health_workers: 0,
    non_academic_staff: 0,
    guests: 0,
    missing_count: 7,
    casualties_count: 0,
    casualties_detail: '9',
    external_item_id: '03:39 PM',
  },
];

// ─── Main ─────────────────────────────────────────────────
async function main() {
  console.log('Starting seed...\n');

  // ── 1. Lookup tables ────────────────────────────────────
  console.log('Seeding lookup tables...');

  // Clusters
  await prisma.cluster.createMany({
    data: CLUSTERS.map((name) => ({ name, is_active: true })),
    skipDuplicates: true,
  });
  console.log(`  clusters: ${CLUSTERS.length}`);

  // Build cluster name → id map (needed for FK inserts below)
  const clusterRecords = await prisma.cluster.findMany({ select: { id: true, name: true } });
  const clusterMap: Record<string, string> = Object.fromEntries(
    clusterRecords.map((c) => [c.name, c.id])
  );

  // Units
  const unitData = Object.entries(UNITS).flatMap(([clusterName, units]) =>
    units.map((name) => ({ name, cluster_id: clusterMap[clusterName], is_active: true }))
  );
  await prisma.unit.createMany({ data: unitData, skipDuplicates: true });
  console.log(`  units: ${unitData.length}`);

  // Locations
  const locationData = Object.entries(LOCATIONS).flatMap(([clusterName, locations]) =>
    locations.map((name) => ({ name, cluster_id: clusterMap[clusterName], is_active: true }))
  );
  await prisma.location.createMany({ data: locationData, skipDuplicates: true });
  console.log(`  locations: ${locationData.length}`);

  // Casualty Conditions
  await prisma.casualtyCondition.createMany({
    data: CASUALTY_CONDITIONS.map((name) => ({ name, is_active: true })),
    skipDuplicates: true,
  });
  console.log(`  casualty_conditions: ${CASUALTY_CONDITIONS.length}`);

  // Damage Report
  await prisma.damageCondition.createMany({
    data: DAMAGE_CONDITION.map((name) => ({ name, is_active: true })),
    skipDuplicates: true,
  });
  console.log(`  damage_conditions: ${DAMAGE_CONDITION.length}`);

  // Positions
  await prisma.position.createMany({
    data: POSITIONS.map((name) => ({ name, is_active: true })),
    skipDuplicates: true,
  });
  console.log(`  positions: ${POSITIONS.length}`);

  // User Types
  const userTypeNames = Object.values(USER_TYPES);
  await prisma.userType.createMany({
    data: userTypeNames.map((name) => ({ name, is_active: true })),
    skipDuplicates: true,
  });
  console.log(`  user_types: ${userTypeNames.length}`);

  // Event Statuses
  await prisma.eventStatus.createMany({
    data: EVENT_STATUSES.map((name) => ({ name, is_active: true })),
    skipDuplicates: true,
  });
  console.log(`  event_statuses: ${EVENT_STATUSES.length}`);

  const statusRecords = await prisma.eventStatus.findMany({ select: { id: true, name: true } });
  const statusMap: Record<string, string> = Object.fromEntries(
    statusRecords.map((s) => [s.name, s.id])
  );

  const unitRecords = await prisma.unit.findMany({
    select: {
      id: true,
      name: true,
      cluster: {
        select: { name: true },
      },
    },
  });
  const unitMap: Record<string, string> = Object.fromEntries(
    unitRecords.map((u) => [`${u.cluster.name}:${u.name}`, u.id])
  );

  // ── 3. Events — one per quarter ─────────────────────────
  console.log('\nSeeding events...');

  const quarters = [...new Set(REPORT_DATA.map((r: any) => r.quarter as string))].sort();
  const eventMap: Record<string, string> = {};

  for (const quarter of quarters) {
    const dates = QUARTER_DATES[quarter];
    const event = await prisma.event.create({
      data: {
        name: `NSED Earthquake Drill ${quarter}`,
        description: `National Simultaneous Earthquake Drill - ${quarter}`,
        quarter,
        status_id: statusMap['completed'],
        started_at: dates.started_at,
        ended_at: dates.ended_at,
      },
    });
    eventMap[quarter] = event.id;
    console.log(`  ${event.name}`);
  }

  // ── 4. Reports ───────────────────────────────────────────
  console.log('\nSeeding reports...');

  let count = 0;
  for (const r of REPORT_DATA as any[]) {
    const event_id = eventMap[r.quarter];
    if (!event_id) {
      console.warn(`  Skipping — no event for quarter: ${r.quarter}`);
      continue;
    }

    await prisma.report.create({
      data: {
        event_id,
        cluster_id: clusterMap[r.cluster],
        unit_id: unitMap[`${r.cluster}:${r.unit}`] ?? null,
        faculty_members: r.faculty_members,
        admin_members: r.admin_members,
        reps_members: r.reps_members,
        ra_members: r.ra_members,
        students: r.students,
        philcare_staff: r.philcare_staff,
        security_personnel: r.security_personnel,
        construction_workers: r.construction_workers,
        tenants: r.tenants,
        health_workers: r.health_workers,
        non_academic_staff: r.non_academic_staff,
        guests: r.guests,
        missing_count: r.missing_count,
        casualties_count: r.casualties_count,
        external_item_id: r.external_item_id || null,
        submitted_at: QUARTER_DATES[r.quarter].started_at,
      },
    });
    count++;
  }

  console.log(`\nSeed complete!`);
  console.log(`  Events:  ${quarters.length}`);
  console.log(`  Reports: ${count}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
